name: food_input
description:  A repository for managing food nutrition data using remote APIs.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  remote_api:
    path: ../../data/remote_api
  rxdart: ^0.28.0
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
