name: authentication
description: A library for handling authentication in the platform.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  remote_api:
    path: ../../data/remote_api
  local_storage:
    path: ../../data/local_storage

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
