name: fitness_nutrition
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  rxdart: ^0.28.0
  remote_api:
    path: ../../data/remote_api
  local_storage:
    path: ../../data/local_storage

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
