name: food_report
description: A library for managing and interacting with food nutrition data, including reading, updating, and deleting food nutrition records.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  remote_api:
    path: ../../data/remote_api

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
